const database = [
    {
        "id_veiculo": 1,
        "modelo_veiculo": "FERRARI SF90",
        "descricao_veiculo": "3.9 V8 TURBO PHEV STRADALE F1-DCT",
        "valor_veiculo": "R$ 6.590.000",
        "cor_veiculo": "Vermelho",
        "portas_veiculo": 2,
        "combustivel_veiculo": "Gasolina e elétrico",
        "categoria_veiculo": "Cupê",
        "cambio_veiculo": "Automática",
        "kilometragem_veiculo": 209,
        "ano_veiculo": "2021/2022",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202209/20220902/ferrari-sf90-3.9-v8-turbo-phev-stradale-f1dct-wmimagem09152210168.jpg"
    },
    {
        "id_veiculo": 2,
        "modelo_veiculo": "JAGUAR F-TYPE",
        "descricao_veiculo": "2.0 P300 GASOLINA R-DYNAMIC BLACK CABRIO AUTOMÁTICO",
        "valor_veiculo": "R$ 700.000",
        "cor_veiculo": "Preto",
        "portas_veiculo": 2,
        "combustivel_veiculo": "Gasolina",
        "categoria_veiculo": "Conversível",
        "cambio_veiculo": "Automática",
        "kilometragem_veiculo": 0,
        "ano_veiculo": "2021/2022",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202208/20220804/jaguar-ftype-2.0-p300-gasolina-rdynamic-black-cabrio-automatico-wmimagem16125461710.jpg"
    },
    {
        "id_veiculo": 3,
        "modelo_veiculo": "PORSCHE 911",
        "descricao_veiculo": "3.0 24V H6 GASOLINA CARRERA PDK",
        "valor_veiculo": "R$ 939.000",
        "cor_veiculo": "Azul",
        "portas_veiculo": 2,
        "combustivel_veiculo": "Gasolina",
        "categoria_veiculo": "Cupê",
        "cambio_veiculo": "Automática",
        "kilometragem_veiculo": 7.020,
        "ano_veiculo": "2020/2021",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202209/20220922/porsche-911-3.0-24v-h6-gasolina-carrera-pdk-wmimagem10531787110.jpg"
    },
    {
        "id_veiculo": 4,
        "modelo_veiculo": "BMW M3",
        "descricao_veiculo": "3.0 I6 TWINTURBO GASOLINA COMPETITION M STEPTRONIC",
        "valor_veiculo": "R$ 809.900",
        "cor_veiculo": "Branco",
        "portas_veiculo": 4,
        "combustivel_veiculo": "Gasolina",
        "categoria_veiculo": "Sedã",
        "cambio_veiculo": "Automática",
        "kilometragem_veiculo": 5.300,
        "ano_veiculo": "2021/2022",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202208/20220819/bmw-m3-3.0-i6-twinturbo-gasolina-competition-m-steptronic-wmimagem11272077020.jpg"
    },
    {
        "modelo_veiculo": "HONDA CIVIC",
        "descricao_veiculo": "2.0 16V FLEXONE EXL 4P CVT",
        "valor_veiculo": "R$ 128.900",
        "cor_veiculo": "Preto",
        "portas_veiculo": 4,
        "combustivel_veiculo": "Gasolina e álcool",
        "categoria_veiculo": "Sedã",
        "cambio_veiculo": "CVT",
        "kilometragem_veiculo": 25.100,
        "ano_veiculo": "2019/2019",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202209/20220922/honda-civic-2.0-16v-flexone-exl-4p-cvt-wmimagem11302630727.jpg"
    },
    {
        "modelo_veiculo": "TOYOTA SUPRA",
        "descricao_veiculo": "3.0 I6 TURBO GASOLINA A91-CF EDITION AUTOMÁTICO",
        "valor_veiculo": "R$ 1.350.000",
        "cor_veiculo": "Branco",
        "portas_veiculo": 2,
        "combustivel_veiculo": "Gasolina",
        "categoria_veiculo": "Cupê",
        "cambio_veiculo": "Automática",
        "kilometragem_veiculo": 0,
        "ano_veiculo": "2021/2022",
        "imagem_veiculo": "https://image.webmotors.com.br/_fotos/anunciousados/gigante/2022/202210/20221013/toyota-supra-3.0-i6-turbo-gasolina-a91cf-edition-automatico-wmimagem15195706416.jpg"
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    {
        "modelo_veiculo": "",
        "descricao_veiculo": "",
        "valor_veiculo": "",
        "cor_veiculo": "",
        "portas_veiculo": ,
        "combustivel_veiculo": "",
        "categoria_veiculo": "",
        "cambio_veiculo": "",
        "kilometragem_veiculo": ,
        "ano_veiculo": "",
        "imagem_veiculo": ""
    },
    // {
    //     "modelo_veiculo": "",
    //     "descricao_veiculo": "",
    //     "valor_veiculo": "",
    //     "cor_veiculo": "",
    //     "portas_veiculo": ,
    //     "combustivel_veiculo": "",
    //     "categoria_veiculo": "",
    //     "cambio_veiculo": "",
    //     "kilometragem_veiculo": ,
    //     "ano_veiculo": "",
    //     "imagem_veiculo": ""
    // }
]

export {database}